start transaction;
insert into Product values('Netto', 1, 'Vegetable');
insert into Product values('Netto', 2, 'Vegetable');
insert into Product values('Netto', 3, 'Vegetable');
insert into Product values('Netto', 4, 'Vegetable');
insert into Product values('Netto', 5, 'Vegetable');
insert into Product values('Netto', 6, 'Vegetable');
insert into Product values('REMA 1000', 7, 'Vegetable');
insert into Product values('REMA 1000', 8, 'Vegetable');
insert into Product values('REMA 1000', 9, 'Vegetable');
insert into Product values('REMA 1000', 10, 'Vegetable');
insert into Product values('REMA 1000', 20, 'Vegetable');
insert into Product values('Foetex', 11, 'Vegetable');
insert into Product values('Foetex', 12, 'Vegetable');
insert into Product values('Foetex', 13, 'Vegetable');
insert into Product values('Foetex', 14, 'Vegetable');
insert into Product values('Foetex', 15, 'Vegetable');
insert into Product values('Lidl', 16, 'Vegetable');
insert into Product values('Lidl', 17, 'Vegetable');
insert into Product values('Lidl', 18, 'Vegetable');
insert into Product values('Lidl', 19, 'Vegetable');
insert into Product values('Meny', 21, 'Vegatable');
insert into Product values('Meny', 22, 'Vegatable');
insert into Product values('Meny', 23, 'Vegatable');
insert into Product values('Meny', 24, 'Vegatable');
insert into Product values('Meny', 25, 'Vegatable');
insert into Product values('Meny', 26, 'Vegatable');

insert into Product values('Netto', 27, 'Meat');
insert into Product values('Netto', 28, 'Meat');
insert into Product values('Netto', 29, 'Meat');
insert into Product values('Netto', 30, 'Meat');
insert into Product values('Netto', 31, 'Meat');
insert into Product values('Foetex', 32, 'Meat');
insert into Product values('Foetex', 33, 'Meat');
insert into Product values('Foetex', 34, 'Meat');
insert into Product values('Foetex', 35, 'Meat');
insert into Product values('Foetex', 36, 'Meat');
insert into Product values('Foetex', 37, 'Meat');
insert into Product values('REMA 1000', 38, 'Meat');
insert into Product values('REMA 1000', 39, 'Meat');
insert into Product values('REMA 1000', 40, 'Meat');
insert into Product values('REMA 1000', 41, 'Meat');
insert into Product values('REMA 1000', 42, 'Meat');
insert into Product values('Lidl', 43, 'Meat');
insert into Product values('Lidl', 44, 'Meat');
insert into Product values('Lidl', 45, 'Meat');
insert into Product values('Lidl', 46, 'Meat');
insert into Product values('Lidl', 47, 'Meat');
insert into Product values('Lidl', 48, 'Meat');
insert into Product values('Meny', 49, 'Meat');
insert into Product values('Meny', 50, 'Meat');
insert into Product values('Meny', 51, 'Meat');
insert into Product values('Meny', 52, 'Meat');

insert into Product values('Netto', 60, 'Dairy');
insert into Product values('Netto', 61, 'Dairy');
insert into Product values('Netto', 62, 'Dairy');
insert into Product values('Netto', 63, 'Dairy');
insert into Product values('Netto', 64, 'Dairy');
insert into Product values('REMA 1000', 65, 'Dairy');
insert into Product values('REMA 1000', 66, 'Dairy');
insert into Product values('REMA 1000', 67, 'Dairy');
insert into Product values('REMA 1000', 68, 'Dairy');
insert into Product values('REMA 1000', 69, 'Dairy');
insert into Product values('Foetex', 70, 'Dairy');
insert into Product values('Foetex', 71, 'Dairy');
insert into Product values('Foetex', 72, 'Dairy');
insert into Product values('Foetex', 73, 'Dairy');
insert into Product values('Foetex', 74, 'Dairy');
insert into Product values('Lidl', 75, 'Dairy');
insert into Product values('Lidl', 76, 'Dairy');
insert into Product values('Lidl', 77, 'Dairy');
insert into Product values('Lidl', 78, 'Dairy');
insert into Product values('Lidl', 79, 'Dairy');
insert into Product values('Nemy', 80, 'Dairy');
insert into Product values('Nemy', 81, 'Dairy');
insert into Product values('Nemy', 82, 'Dairy');
insert into Product values('Nemy', 83, 'Dairy');
insert into Product values('Nemy', 84, 'Dairy');

insert into Product values('Netto', 90, 'Colonial');
insert into Product values('Netto', 91, 'Colonial');
insert into Product values('Netto', 92, 'Colonial');
insert into Product values('Netto', 93, 'Colonial');
insert into Product values('Netto', 94, 'Colonial');
insert into Product values('Netto', 95, 'Colonial');
insert into Product values('REMA 1000', 96, 'Colonial');
insert into Product values('REMA 1000', 97, 'Colonial');
insert into Product values('REMA 1000', 98, 'Colonial');
insert into Product values('REMA 1000', 99, 'Colonial');
insert into Product values('REMA 1000', 100, 'Colonial');
insert into Product values('Foetex', 110, 'Colonial');
insert into Product values('Foetex', 111, 'Colonial');
insert into Product values('Foetex', 112, 'Colonial');
insert into Product values('Foetex', 113, 'Colonial');
insert into Product values('Foetex', 114, 'Colonial');
insert into Product values('Foetex', 115, 'Colonial');
insert into Product values('Lidl', 101, 'Colonial');
insert into Product values('Lidl', 102, 'Colonial');
insert into Product values('Lidl', 103, 'Colonial');
insert into Product values('Meny', 104, 'Colonial');
insert into Product values('Meny', 105, 'Colonial');
insert into Product values('Meny', 106, 'Colonial');
insert into Product values('Meny', 107, 'Colonial');
insert into Product values('Meny', 108, 'Colonial');
insert into Product values('Meny', 109, 'Colonial');

insert into Vegetable values(1, 'Apple', 10); 
insert into Vegetable values(7, 'Apple', 6); 
insert into Vegetable values(11, 'Apple', 15); 
insert into Vegetable values(16, 'Apple', 8); 
insert into Vegetable values(21, 'Apple', 15);
insert into Vegetable values(2, 'Cucumber', 10);
insert into Vegetable values(8, 'Cucumber', 7);
insert into Vegetable values(12, 'Cucumber', 12);
insert into Vegetable values(22, 'Cucumber', 13);
insert into Vegetable values(3, 'Tomato', 10);
insert into Vegetable values(9, 'Tomato', 13);
insert into Vegetable values(13, 'Tomato', 8);
insert into Vegetable values(17, 'Tomato', 6);
insert into Vegetable values(23, 'Tomato', 3);
insert into Vegetable values(4, 'Broccoli', 10);
insert into Vegetable values(10, 'Broccoli', 11);
insert into Vegetable values(14, 'Broccoli', 15);
insert into Vegetable values(18, 'Broccoli', 5);
insert into Vegetable values(24, 'Broccoli', 12);
insert into Vegetable values(5, 'Banana', 7);
insert into Vegetable values(20, 'Banana', 4);
insert into Vegetable values(15, 'Banana', 10);
insert into Vegetable values(19, 'Banana', 8);
insert into Vegetable values(25, 'Banana', 12);
insert into Vegetable values(6, 'Eggplant', 12);
insert into Vegetable values(26, 'Eggplant', 10);

insert into Meat values(27, 'Chicken', 59);
insert into Meat values(32, 'Chicken', 68);
insert into Meat values(38, 'Chicken', 62);
insert into Meat values(43, 'Chicken', 48);
insert into Meat values(49, 'Chicken', 64);
insert into Meat values(28, 'Ground beef', 99);
insert into Meat values(33, 'Ground beef', 105);
insert into Meat values(39, 'Ground beef', 110);
insert into Meat values(44, 'Ground beef', 102);
insert into Meat values(50, 'Ground beef', 104);
insert into Meat values(29, 'Salmon', 125);
insert into Meat values(34, 'Salmon', 122);
insert into Meat values(40, 'Salmon', 126);
insert into Meat values(45, 'Salmon', 134);
insert into Meat values(51, 'Salmon', 149);
insert into Meat values(46, 'Duck', 52);
insert into Meat values(35, 'Duck', 55);
insert into Meat values(30, 'Pork', 90);
insert into Meat values(36, 'Pork', 110);
insert into Meat values(41, 'Pork', 95);
insert into Meat values(47, 'Pork', 88);
insert into Meat values(52, 'Pork', 89);
insert into Meat values(31, 'Ribeye', 423);
insert into Meat values(37, 'Ribeye', 425);
insert into Meat values(42, 'Ribeye', 545);
insert into Meat values(48, 'Ribeye', 499);

insert into Dairy values(60, 'Milk', 10);
insert into Dairy values(65, 'Milk', 12);
insert into Dairy values(70, 'Milk', 9);
insert into Dairy values(75, 'Milk', 7);
insert into Dairy values(80, 'Milk', 13);
insert into Dairy values(61, 'Butter', 120);
insert into Dairy values(66, 'Butter', 123);
insert into Dairy values(71, 'Butter', 119);
insert into Dairy values(76, 'Butter', 112);
insert into Dairy values(81, 'Butter', 131);
insert into Dairy values(62, 'Cream', 31);
insert into Dairy values(67, 'Cream', 29);
insert into Dairy values(72, 'Cream', 32);
insert into Dairy values(77, 'Cream', 27);
insert into Dairy values(82, 'Cream', 35);
insert into Dairy values(63, 'Skyr', 16);
insert into Dairy values(68, 'Skyr', 21);
insert into Dairy values(73, 'Skyr', 22);
insert into Dairy values(78, 'Skyr', 18);
insert into Dairy values(83, 'Skyr', 24);
insert into Dairy values(64, 'Yogurt', 18);
insert into Dairy values(69, 'Yogurt', 20);
insert into Dairy values(74, 'Yogurt', 19);
insert into Dairy values(79, 'Yogurt', 22);
insert into Dairy values(84, 'Yogurt', 17);

insert into Colonial values(90, 'Pasta', 10);
insert into Colonial values(96,'Pasta',9);
insert into Colonial values(110,'Pasta',14);
insert into Colonial values(101,'Pasta',5);
insert into Colonial values(104,'Pasta',13);
insert into Colonial values(91,'Rice',16);
insert into Colonial values(97,'Rice',20);
insert into Colonial values(111,'Rice',15);
insert into Colonial values(102,'Rice',17);
insert into Colonial values(105,'Rice',10);
insert into Colonial values(92,'Salsa',43);
insert into Colonial values(98,'Salsa',55);
insert into Colonial values(112,'Salsa',32);
insert into Colonial values(103,'Salsa',20);
insert into Colonial values(106,'Salsa',50);
insert into Colonial values(93,'Oliveoil',111);
insert into Colonial values(99,'Oliveoil',70);
insert into Colonial values(113,'Oliveoil',215);
insert into Colonial values(107,'Oliveoil',140);
insert into Colonial values(94,'Ketchup',50);
insert into Colonial values(100,'Ketchup',55);
insert into Colonial values(114,'Ketchup',40);
insert into Colonial values(108,'Ketchup',45);
insert into Colonial values(95,'Mayonnaise',25);
insert into Colonial values(115,'Mayonnaise',20);
insert into Colonial values(109,'Mayonnaise',30);


commit;